name: Discord Notification On Failure
on:
  workflow_call:

jobs:
  notify-on-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: send Discord message with args
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_BC_CI_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_BC_CI_WEBHOOK_TOKEN }}
          color: "#ff0000"
          username: ${{ github.repository }}
          args: test test [test link](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})
          message: | 
            PR ${{ github.event.pull_request.number }}: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
            
            ${{ github.triggering_actor }} broke the workflow \"${{ github.workflow }}\"